# Generated by Django 3.1.5 on 2021-01-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentimentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimentType', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative')], max_length=3)),
                ('emotionType', models.CharField(choices=[('NET', 'Neutral'), ('EMP', 'Empty'), ('SAD', 'Sadness'), ('ENT', 'Enthusiasm'), ('WOR', 'Worry'), ('SUR', 'Surprise'), ('LOV', 'Love'), ('FUN', 'Fun'), ('HAT', 'Hate'), ('HAP', 'Happiness'), ('BOR', 'Boredom'), ('REL', 'Relief'), ('ANG', 'Anger')], max_length=3)),
                ('textReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.sentimenttext')),
            ],
        ),
    ]
