# Generated by Django 3.1.5 on 2021-01-28 10:09

import analysis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentimentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentialAddress', models.TextField(max_length=512, validators=[analysis.models.validate_numeric, django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
