# Generated by Django 3.1.3 on 2021-01-26 10:34

from django.db import migrations, models
import sentimental_analysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimental_analysis', '0002_auto_20210126_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textarea',
            name='text',
            field=models.TextField(max_length=1000, validators=[sentimental_analysis.models.numeric]),
        ),
    ]
